#!/bin/bash

isVerbose() {
    if [ $verbose -eq 1 ]
    then
        # Print a trace of simple commands, for commands, case commands, select commands, and arithmetic for commands
        # and their arguments or associated word lists after they are expanded and before they are executed.
        # The value of the PS4 variable is expanded and the resultant value is printed before the command and its expanded arguments.
        # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
        # Alias set -o xtrace
        set -xv
    fi
}


validateRunner() {
    if [ $(id -u) -eq 0 ]
    then
        tput setaf 1
        echo "Running as root is not allowed. Exiting ..."
        tput setaf 9
        exit 1
    else
        echo "Running as $USER ..."
    fi
}


showHelp() {
    # `cat << EOF` This means that cat should stop reading when EOF is detected
    cat << EOF
Usage: ./installer -v <espo-version> [-hV]
Install Pre-requisites for EspoCRM with docker in Development mode

    -h,Display help

    -v,Set and Download specific version of EspoCRM

    -V,Run script in verbose mode. Will print out each step of execution.

Pre Installation:
1) Go to Docker Preferences => File Sharing
2) Add /crm path, otherwise mount will fail.

EOF
# EOF is found above and hence cat command stops reading. This is equivalent to echo but much neater when printing out.
}


validateRunner

# Command-line Option builder and parser
export verbose=0;

# Documentation on getopts:
# https://www.linkedin.com/pulse/command-line-named-parameters-bash-karthik-bhat-k/

# Removed getopt as it doesn't work well with Mac
while getopts "hv:V" FLAG
do
    case $FLAG in
        h)
            showHelp
            exit 0
            ;;
        v)
            shift
            export version=$1
            ;;
        V)
            export verbose=1
            ;;
        \?)
            showHelp
            exit 0
            ;;
    esac
    shift
done


# See if version is set
if [ -z $version ];
then
    tput setaf 1;
    echo "ERROR: Version not found";
    tput init;
    showHelp;
    exit 1;
fi

if [ $(pwd) != "/crm" ];
then
  echo "Expected path: /crm";
fi

# This is to build images
docker build -f webapp/Dockerfile -t crm-webapp:1.0.0 --build-arg VERSION=$version .

export WORKDIR=$(pwd);
export CRMDIR=$WORKDIR/espocrm;
export PROJECTS=$WORKDIR/projects;
python $WORKDIR/repo_tools/install.py

if [ ! -d $CRMDIR ];
then
    cd $WORKDIR;
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
    brew install wget --with-libressl;
    wget -O /tmp/espocrm.zip https://github.com/espocrm/espocrm/archive/$version.zip;
    unzip -d . /tmp/espocrm.zip;
    mv espocrm-$version espocrm;
else
    echo "EspoCRM repository already exists";
fi

cd $CRMDIR;

docker run --rm -v $(pwd):/app composer:1.7.2 install -o --ignore-platform-reqs;

if [ ! -d $CRMDIR/build/EspoCRM-$version ];
then
    docker run --rm -v $(pwd):/app node:8.12.0-alpine sh -c "cd /app; npm install; npm install -g grunt-cli; grunt"
fi

cd $WORKDIR;

# This is to add extensions after building images.
docker-compose -f dev.docker-compose.yml up -d
docker exec devCrmServer chown -R nobody:nogroup $CRMDIR

cat << EOF

Special Note: After reboot, no need to use sudo while running docker command!

EOF
