#!/bin/sh

# Running nginx in background
nginx -c /etc/nginx/nginx.conf

echo "* * * * * cd /crm/espocrm; /usr/bin/php -f cron.php > /dev/null 2>&1" | crontab -u nobody -

# Running php-fpm. -F to run in foreground and -R to run as root
php-fpm7 -F
